server:
  port: 14033

spring:
  application:
    name: sentinel-feign-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
