server:
  port: 11072

spring:
  application:
    name: ofc-bus-config-server
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://gitee.com/soulballad/spring-usage-examples.git
          # 对应 {label} 部分，即 Git 的分支
          default-label: master
          # 仓库文件夹名称，多个以逗号分隔
          search-paths: spring-cloud/spring-cloud-03-official/spring-cloud-ofc-07-bus/config-repo
          # git 仓库用户名（公开库可以不用填写）
          username:
          # git 仓库密码（公开库可以不用填写）
          password:
    bus:
      # 开启消息跟踪
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
  kafka:
    consumer:
      # 指定默认消费者 group id
      # 如果不设置，将会使用 commons 工程中的 group-id，那时调用 /actuator/bus-refresh 接口只会刷新其中一个 client
      # 因为在同一个组中的 Consumer，同一个主题只会被一个 Consumer 接收
      group-id: ofc-bus-config-server-consumer-group

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  server:
    port: 11070
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        # 开启 endpoint
        include: bus-refresh
