server:
  port: 14008

spring:
  application:
    name: alb-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos

management:
  endpoints:
    web:
      exposure:
        include: "*"
