server:
  port: 14010

dubbo:
  scan:
    base-packages: com.soulballad.usage.springcloud
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registries:
    new:
      address: spring-cloud://localhost
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata