###  GET /provider/user/list
GET http://localhost:8090/provider/user/list
Accept: application/json

###  GET /provider/user/query/{id}
GET http://localhost:8090/provider/user/query/1
Accept: application/json

###  POST /provider/user/add
POST http://localhost:8090/provider/user/add
Accept: application/json
Content-Type: application/json

{
  "name": "wangwu",
  "age": 20,
  "birthday": "2000-01-01",
  "address": "wuhan",
  "phone": "15999999999"
}

###  PUT /provider/user/update
PUT http://localhost:8090/provider/user/update
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "name": "lisi",
  "age": 40,
  "birthday": "1980-01-01",
  "address": "guangzhou",
  "phone": "13888888888"
}

###  DELETE /provider/user/delete/{id}
DELETE http://localhost:8090/provider/user/delete/3
Accept: application/json
