server:
  port: 14011

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    # subscribed provider service
    subscribed-services: ${provider.application.name}

  consumer:
    check: false

provider:
  application:
    name: alb-dubbo-provider
