################################################ nfx-asm-archaius ################################################
### GET /orderPoint
GET http://localhost:7010/config/orderPoint

### GET /userLevel
GET http://localhost:7010/config/userLevel


################################################ nfx-asm-eureka ################################################
### GET 8011
GET http://localhost:8011/
### GET 8012
GET http://localhost:8012/


################################################ nfx-asm-order-service ################################################
### GET /order/list
GET http://localhost:11016/order/list
### GET /order/find?orderCode=?
GET http://localhost:11016/order/find?orderCode=OC20200609211952001
### POST /order/create
POST http://localhost:11016/order/create
Accept: application/json
Content-Type: application/json

{
  "userId": 2,
  "orderCode": "OC20200609213933001",
  "totalMoney": 12343.48,
  "orderDate": "2020-06-09 21:39:33",
  "status": "wait"
}
### PUT /order/pay
PUT http://localhost:11016/order/pay
Content-Type: application/json

{
  "id": 5
}
### GET /order/queryByCondition
GET http://localhost:11016/order/queryByCondition
Accept: application/json
Content-Type: application/json

{
  "userId": 2,
  "orderCode": "OC20200609",
  "totalMoney": 20,
  "orderStartDate": "2020-02-10 16:17:12",
  "orderEndDate": "2020-06-30 16:17:12"
}


################################################ nfx-asm-user-service ################################################
### GET /user/list
GET http://localhost:11027/user/list
### GET /user/query/{id}
GET http://localhost:11027/user/query/1
### GET /user/find?name=?
GET http://localhost:11027/user/find?name=zhangsan
### GET /user/udpate
PUT http://localhost:11027/user/update
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "name": "zhaoliu",
  "age": 31,
  "birthday": "1979-02-03",
  "address": "guangzhou",
  "phone": "16999999999",
  "money": 2222.22,
  "points": 336
}


################################################ nfx-asm-zuul ################################################
### nfx-asm-order-service
### GET /order/find?orderCode=?
GET http://localhost:9090/nfx-asm-order-service/order/find?orderCode=OC20200609211952001

### nfx-asm-user-service
### GET /user/find?name=?
GET http://localhost:9090/nfx-asm-user-service/user/find?name=zhangsan
