### GET /user/list
GET http://localhost:8080/user/list
Accept: application/json

### GET /user/list
GET http://localhost:8080/user/find/1 // 200 OK
#GET http://localhost:8080/user/find/100 // 404 Not Found
Accept: application/json

### POST /user/add
POST http://localhost:8080/user/add
Accept: application/json
Content-Type: application/json

{
  "name": "wangwu",
  "age": 25,
  "birthday": "1995-06-23",
  "address": "guangzhou",
  "phone": "13777777777"
}

### PUT /user/update success
PUT http://localhost:8080/user/update
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "name": "lisi2",
  "age": 32,
  "birthday": "1988-03-23",
  "address": "shanghai2",
  "phone": "13888888882"
}

### PUT /user/update fail  // 404 Not Found (id)
PUT http://localhost:8080/user/update
Accept: application/json
Content-Type: application/json

{
  "id": 222,
  "name": "lisi2",
  "age": 32,
  "birthday": "1988-03-23",
  "address": "shanghai2",
  "phone": "13888888882"
}

### DELETE /user/delete/3
#DELETE http://localhost:8080/user/delete/30
DELETE http://localhost:8080/user/delete/3 // 200 OK
Accept: application/json