server:
  port: 14010

dubbo:
  scan:
    base-packages: com.soulballad.usage.springcloud
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9900
      server: netty
  registry:
    address: spring-cloud://localhost
feign:
  hystrix:
    enabled: true
