### 使用密码模式获取令牌
POST http://localhost:11103/oauth/token?client_id=soulballad&client_secret=admin123456&grant_type=password&username=zhangsan&password=123456

### 访问资源
GET http://localhost:11103/user/getUser?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTI4MzE3NTcsInVzZXJfbmFtZSI6InpoYW5nc2FuIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI1YmQzNDcwZi0zNWEzLTQwOTQtOWY5Ny1hYjg1Njk3MDAzZGUiLCJjbGllbnRfaWQiOiJzb3VsYmFsbGFkIiwic2NvcGUiOlsiYWxsIl19.0kaeK2IrQ0bjnLTNwzDJlLEkgO8lQOCHcRQ32fAmuW8


### 使用 Authorization https://www.cnblogs.com/fengzheng/p/11724625.html
### Authorization = Basic + " " + base64(clientId:clientSecret); https://www.sojson.com/base64.html
POST http://localhost:11103/oauth/token?grant_type=password&username=zhangsan&password=123456&scope=all
Accept: */*
Cache-Control: no-cache
Authorization: Basic c291bGJhbGxhZDphZG1pbjEyMzQ1Ng==

### 访问资源
GET http://localhost:11103/user/currentUser
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTI4MzE4NjAsInVzZXJfbmFtZSI6InpoYW5nc2FuIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiJjNWUyYzBmMi1mNDNmLTQzZDItYWZlNS0xNDg4YWI2MGFlMTQiLCJjbGllbnRfaWQiOiJzb3VsYmFsbGFkIiwic2NvcGUiOlsiYWxsIl19.Lq_XBnFx_OkFT3NTmaBheLIN0resVcFF_dpO72z2Lpo
