### GET /user/list
GET http://localhost:8080/user/list
Accept: application/json

### GET /user/get/{id}
GET http://localhost:8080/user/get/1
Accept: application/json

### POST /user/add success
POST http://localhost:8080/user/add
Content-Type: application/json
Accept: */*
Cache-Control: no-cache

{
  "name": "zhaoliu",
  "age": 43,
  "idCard": "110101200303072399"
}

### POST /user/add idCard&name&age illegal
POST http://localhost:8080/user/add
Content-Type: application/json
Accept: */*
#Accept-Language: en_US 使用此配置可选择中、英文错误提示

{
  "name": "s",
  "age": 243,
  "idCard": "1101003072399"
}

### PUT /user/update success
PUT http://localhost:8080/user/update
Content-Type: application/json
Accept: */*

{
  "id": 2,
  "name": "sunqi",
  "age": 43,
  "idCard": "110101200303072399"
}

### DELETE /user/delete/{id} success
DELETE http://localhost:8080/user/delete/1
Content-Type: application/json
Accept: */*

