ofc-oauth2-sso-server: http://localhost:11103
server:
  port: 11105

spring:
  application:
    name: ofc-oauth2-sso-client
security:
  oauth2:
    client:
      client-id: soulballad
      client-secret: 123456
      user-authorization-uri: ${ofc-oauth2-sso-server}/oauth/authorize
      access-token-uri: ${ofc-oauth2-sso-server}/oauth/token
    resource:
      jwt:
        key-uri: ${ofc-oauth2-sso-server}/oauth/token_key
